services:
  database:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: hatfield
      POSTGRES_DB: cogdb
    volumes:
      - db-cog-upload-service:/data
  adminer:
      image: adminer
      restart: always
      depends_on: 
        - database
      ports:
        - 8080:8080
  app:
      build: .
      container_name: server-cogapp
      command: uvicorn main:app --host 0.0.0.0 --port 8000 
      ports:
        - 8000:8000
      volumes:
        - .:/server-app 

volumes:
  db-cog-upload-service:
  .: